site_name: Gufo Thor
site_description: Gufo Thor Documentation
site_author: Gufo Labs
site_url: "https://docs.gufolabs.com/gufo_thor/"
copyright: "&copy; 2023, Gufo Labs"
site_dir: dist/docs/
repo_url: https://github.com/gufolabs/gufo_thor/
repo_name: gufolabs/gufo_thor
nav:
  - Home: index.md
  - Installation: installation.md
  # - Man Pages:
  #     - Overview: man/index.md
  #     - gufo-thor: man/gufo-thor.md
  - Reference:
      - Overview: reference/index.md
      - Command Line: reference/cli.md
      - Config: reference/
      - Configuration Templates: reference/templates.md
      - Code: reference/code/
  - Developers' Guide:
      - Overview: dev/index.md
      - Developer's Environment: dev/environment.md
      - Building and Testing: dev/testing.md
      - Common Tasks: dev/common.md
      - Code Quality: dev/codequality.md
      - Code Base: dev/codebase.md
      - Contributing Guide: dev/CONTRIBUTING.md
      - Code of Conduct: dev/CODE_OF_CONDUCT.md
      - Supported Standards: dev/standards.md
  - FAQ: faq.md
  - Changelog: CHANGELOG.md
  - License: LICENSE.md
  # Users
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      primary: deep purple
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
watch:
  - docs/
  - src/gufo/
plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_doc_stubs.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_submodules: false
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - attr_list
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: True
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  analytics:
    provider: google
    property: G-GW3X378HNJ
