installation_name: >
  {{installation_name}}
pg:
  db: noc
  user: noc
  password: noc
web:
  theme: >
    {{theme}}
msgstream:
  client_class: noc.core.msgstream.redpanda.RedPandaClient
redpanda:
  addresses: kafka:9092
